export default {
  "122dbed4": [() => import(/* webpackChunkName: "122dbed4" */ "@site/docs/hardware-requirements.md"), "@site/docs/hardware-requirements.md", require.resolveWeak("@site/docs/hardware-requirements.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "2ab8ccb5": [() => import(/* webpackChunkName: "2ab8ccb5" */ "@site/docs/weekly-breakdown.md"), "@site/docs/weekly-breakdown.md", require.resolveWeak("@site/docs/weekly-breakdown.md")],
  "5a081de0": [() => import(/* webpackChunkName: "5a081de0" */ "@site/docs/chapters/digital-twin.mdx"), "@site/docs/chapters/digital-twin.mdx", require.resolveWeak("@site/docs/chapters/digital-twin.mdx")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "713ae4f7": [() => import(/* webpackChunkName: "713ae4f7" */ "@generated/docusaurus-plugin-content-docs/default/p/textbook-frontend-docs-185.json"), "@generated/docusaurus-plugin-content-docs/default/p/textbook-frontend-docs-185.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/textbook-frontend-docs-185.json")],
  "8b222800": [() => import(/* webpackChunkName: "8b222800" */ "@site/docs/learning-outcomes.md"), "@site/docs/learning-outcomes.md", require.resolveWeak("@site/docs/learning-outcomes.md")],
  "9225e2c3": [() => import(/* webpackChunkName: "9225e2c3" */ "@site/docs/chapters/robotic-nervous-system.mdx"), "@site/docs/chapters/robotic-nervous-system.mdx", require.resolveWeak("@site/docs/chapters/robotic-nervous-system.mdx")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "c377a04b": [() => import(/* webpackChunkName: "c377a04b" */ "@site/docs/index.md"), "@site/docs/index.md", require.resolveWeak("@site/docs/index.md")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "d16c5452": [() => import(/* webpackChunkName: "d16c5452" */ "@site/docs/assessments.md"), "@site/docs/assessments.md", require.resolveWeak("@site/docs/assessments.md")],
  "d6295378": [() => import(/* webpackChunkName: "d6295378" */ "@site/docs/chapters/ai-robot-brain.mdx"), "@site/docs/chapters/ai-robot-brain.mdx", require.resolveWeak("@site/docs/chapters/ai-robot-brain.mdx")],};
